### ISSUE TITLE
filename is None sometimes when calling randomtile

### ISSUE THREAD

**Issue by Wreckstation** [TrashMonks/cryptogull#67]
```
Traceback (most recent call last):
Jul 24 15:47:28 nugget pipenv[822711]:   File "/home/cryptogull/.local/share/virtualenvs/cryptogull-7iYW>
Jul 24 15:47:28 nugget pipenv[822711]:     ret = await coro(*args, **kwargs)
Jul 24 15:47:28 nugget pipenv[822711]:   File "/home/cryptogull/cryptogull/cogs/tiles.py", line 133, in >
Jul 24 15:47:28 nugget pipenv[822711]:     return await self.randomtile(ctx, "recolor", "random", readin>
Jul 24 15:47:28 nugget pipenv[822711]:   File "/home/cryptogull/.local/share/virtualenvs/cryptogull-7iYW>
Jul 24 15:47:28 nugget pipenv[822711]:     return await self.callback(self.cog, *args, **kwargs)
Jul 24 15:47:28 nugget pipenv[822711]:   File "/home/cryptogull/cryptogull/cogs/tiles.py", line 88, in r>
Jul 24 15:47:28 nugget pipenv[822711]:     return await(process_tile_request(ctx, name, *args, reading=r>
Jul 24 15:47:28 nugget pipenv[822711]:   File "/home/cryptogull/cryptogull/cogs/tiles.py", line 204, in >
Jul 24 15:47:28 nugget pipenv[822711]:     tile = QudTile(filename, colorstring, colors[0], colors[1], q>
Jul 24 15:47:28 nugget pipenv[822711]:   File "/home/cryptogull/.local/share/virtualenvs/cryptogull-7iYW>
Jul 24 15:47:28 nugget pipenv[822711]:     self.filename = fix_filename(self.filename)  # convert _ into>
Jul 24 15:47:28 nugget pipenv[822711]:   File "/home/cryptogull/.local/share/virtualenvs/cryptogull-7iYW>
Jul 24 15:47:28 nugget pipenv[822711]:     if filename.lower().startswith('assets_content_textures'):
Jul 24 15:47:28 nugget pipenv[822711]: AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by egocarib** [comment]
Seems to occur because this line is passing a `NoneType` filename to the `QudTile` constructor.
https://github.com/TrashMonks/cryptogull/blob/145fd6693c6c31e0243ba2a2aaa4598655618f52/cogs/tiles.py#L204-L205

This should be fixed in the cryptogull function above, but also should probably be handled better in hagadias in one or both of these places:

-  `QudTile` constructor (https://github.com/TrashMonks/hagadias/blob/32a2260902396ca1093b718c77922a84c54ec32f/hagadias/qudtile.py#L71)
- or `fix_filename` function (https://github.com/TrashMonks/hagadias/blob/4ef589a3d4e750393b4e8f2a4f5c6963ca481775/hagadias/qudtile.py#L21).

**Comment by Wreckstation** [comment]
Specifically errors out on objects that have dynamically generated tiles by hagadias's image_provider. A tile exists but no filename
